### ISSUE TITLE
Implement Add Notification route

### ISSUE THREAD

**Issue by JeelRajodiya** [enchanted-oasis-org/Enchanted-Oasis#79]
**Route Details:**
- Method: `POST`
- URL Pattern: `/api/notification`

**Tasks:**
- [x] Implement the Add Notification route.
- [x] Add appropriate handlers and controllers.
- [x] Test the route using sample data.
- [x] Ensure proper error handling.
