### ISSUE TITLE
Implement Remove Notification route

### ISSUE THREAD

**Issue by JeelRajodiya** [enchanted-oasis-org/Enchanted-Oasis#80]
**Route Details:**
- Method: `DELETE`
- URL Pattern: `/api/notification/{notificationId}`

**Tasks:**
- [x] Implement the Remove Notification route.
- [x] Add appropriate handlers and controllers.
- [x] Test the route using sample data.
- [x] Ensure proper error handling.
