### ISSUE TITLE
Implement Edit Notification route

### ISSUE THREAD

**Issue by JeelRajodiya** [enchanted-oasis-org/Enchanted-Oasis#81]
**Route Details:**
- Method: `PUT`
- URL Pattern: `/api/notification/{notificationId}`

**Tasks:**
- [ ] Implement the Edit Notification route.
- [ ] Add appropriate handlers and controllers.
- [ ] Test the route using sample data.
- [ ] Ensure proper error handling.
