### ISSUE TITLE
Implement Get Notification route

### ISSUE THREAD

**Issue by JeelRajodiya** [enchanted-oasis-org/Enchanted-Oasis#82]
**Route Details:**
- Method: `GET`
- URL Pattern: `/api/notification/{notificationId}`

**Tasks:**
- [x] Implement the Get Notification route.
- [x] Add appropriate handlers and controllers.
- [x] Test the route using sample data.
- [x] Ensure proper error handling.
