### ISSUE TITLE
Implement Get Views route

### ISSUE THREAD

**Issue by JeelRajodiya** [enchanted-oasis-org/Enchanted-Oasis#83]
**Route Details:**
- Method: `GET`
- URL Pattern: `/api/notification/{notificationId}/views`

**Tasks:**
- [x] Implement the Get Views route.
- [x] Add appropriate handlers and controllers.
- [x] Test the route using sample data.
- [x] Ensure proper error handling.
