### ISSUE TITLE
Implement Get Viewers route

### ISSUE THREAD

**Issue by JeelRajodiya** [enchanted-oasis-org/Enchanted-Oasis#84]
**Route Details:**
- Method: `GET`
- URL Pattern: `/api/notification/{notificationId}/listViewers`

**Tasks:**
- [x] Implement the Get Viewers route.
- [x] Add appropriate handlers and controllers.
- [x] Test the route using sample data.
- [x] Ensure proper error handling.
