### ISSUE TITLE
Implement mark as seen route

### ISSUE THREAD

**Issue by JeelRajodiya** [enchanted-oasis-org/Enchanted-Oasis#86]
**Route Details:**
- Method: `PATCH`
- URL Pattern: `/api/notification/{notificationId}/seen`

**Tasks:**
- [x] Implement the mark as seen route.
- [x] Add appropriate handlers and controllers.
- [x] Test the route using sample data.
- [x] Ensure proper error handling.
